name: Pulso
configs:
  Debug: debug
  Release: release    
packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    exactVersion: 5.10.2
  Defaults:
    url: https://github.com/sindresorhus/Defaults.git
    exactVersion: 9.0.2
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    exactVersion: 1.9.2
  IsCameraOn:
    url: https://github.com/sindresorhus/is-camera-on.git
    exactVersion: 2.0.2
  Logging:
    url: https://github.com/apple/swift-log.git
    exactVersion: 1.6.3
  KeychainAccess:
    url: https://github.com/kishikawakatsumi/KeychainAccess.git
    exactVersion: 4.2.2
  MenuBarExtraAccess:
    url: https://github.com/orchetect/MenuBarExtraAccess
    exactVersion: 1.2.1
  Realm:
    url: https://github.com/realm/realm-swift.git
    exactVersion: 20.0.2
  WindowAnimation:
    url: https://github.com/Lakr233/WindowAnimation.git
    exactVersion: 1.0.5
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle.git
    exactVersion: 2.7.0
fileGroups:
  - App
targets:
  Pulso:
    type: application
    platform: macOS
    sources:
      - path: App
        excludes:
          - Resources/Info.plist
          - Resources/Pulso.entitlements
    dependencies:
      - package: Alamofire
      - package: Defaults
      - package: Dependencies
      - package: IsCameraOn
      - package: KeychainAccess
      - package: MenuBarExtraAccess
      - package: Realm
        product: RealmSwift
        embed: True
      - package: WindowAnimation
      - package: Sparkle
      - package: Logging
    preBuildScripts:
      - name: SwiftFormat
        basedOnDependencyAnalysis: False
        script: |
                ~/bin/swiftformat --swiftversion 5.10 --config Scripts/.swiftformat "${SRCROOT}/App"
    settings:
      base:
        MARKETING_VERSION: 0.0.2
        CURRENT_PROJECT_VERSION: 2
        DEVELOPMENT_TEAM: XSCH3APH3M
        SWIFT_VERSION: 5
        SDKROOT: macosx
        CLANG_ENABLE_MODULES: YES
        ENABLE_HARDENED_RUNTIME: YES
        MACOSX_DEPLOYMENT_TARGET: 15.0
        ENABLE_TESTABILITY: YES
        CLANG_USE_OPTIMIZATION_PROFILE: NO
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: NO
        DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        SWIFT_OPTIMIZE_OBJECT_LIFETIME: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: App/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: App/Resources/Pulso.entitlements
        PRODUCT_BUNDLE_IDENTIFIER: com.get-pulso.mac
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.social-networking
schemes:
  Pulso:
    build:
      targets:
        Pulso: all
